### ISSUE TITLE
Straggler tubes not showing up in csv file

### ISSUE THREAD

**Issue by wyattks** [episphere/biospecimen#409] opened 2022-09-14 14:57 UTC
During the clinical testing, when we created shipping scenarios with straggler tubes, the straggler tubes did not show up in the csv file.   Some of the tubes not showing up are the ones being added to the file for clinical so that was expected.  Other tubes should have shown up in the file as they already exist for the research collections.  

Examples:

Ship Scenario B using CXA002654
The ACD and Urine tubes were collected after the remainder of the collection was sent to shipping and added to Box 3. Once both tubes were "collected" they were added to the same shipping box. The ACD and Urine tubes did not show up in the csv file.  CXA002654 0005 and CXA002654 0006

Ship Scenario C using CXA123423
The SST tubes were all placed in a box (Box 2) and shipped separately from the remainder of the collection (Box 1). The SST tubes did not show up in the csv file. At least CXA123423 0001 & CXA123423 0002 should have been there.  CXA123423 0011, CXA123423 0012, and CXA123423 0021 are new additions for the clinical collections.

Ship Scenario F using CXA123422
The Heparin tubes were marked as missing when the collection was added to Box 5. They were later added to Box 6 and shipped separately. The heparin tubes did not show up in the csv file. CXA123422 0003 should have been there.  CXA123422 0013 is a new addition for the clinical collections.

**Comment by wyattks** [comment] 2022-10-04 17:42
After latest fix for straggler tubes, they are still not showing up in the csv file.

**Comment by abhinavjonnada82** [comment] 2022-10-12 19:59
PoC:
[10_12_2022-BSI-data-export(5).csv](https://github.com/episphere/biospecimen/files/9768314/10_12_2022-BSI-data-export.5.csv)

**Comment by wyattks** [comment] 2022-10-13 21:14
Ran a test in research and clinical.  Stragglers showed up correctly in csv file for both dashboards.
[Straggler test 10-13-2022.docx](https://github.com/episphere/biospecimen/files/9780703/Straggler.test.10-13-2022.docx)
[CSV testing 10-13-2022.csv](https://github.com/episphere/biospecimen/files/9780704/CSV.testing.10-13-2022.csv)

**Comment by Davinkjohnson** [comment] 2023-05-16 17:18
This is a duplicate of the Shipping Dashboard issue.

**Closed by Davinkjohnson** 2023-05-16 17:18 UTC
Labels: bug, Priority 1
